### ISSUE TITLE
PlayFabSysHttp and PlayFabWinHttp should use singleton HttpClient

### ISSUE THREAD

**Issue by jonbrichoux** [PlayFab/CSharpSDK#95] opened 2017-09-06 18:37 UTC
There are lots of posts on the web about how HttpClient is meant to be re-used, not newed up for each call. Here is one such: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/.

Anyway we're finding that with use of PlayFabServerAPI we're ending up with a lot of sockets left open to playfab. This seems similar to the article above, but slightly different in that these http clients are not being disposed, so the left-open sockets are in a different wait state.

Still, I think it's critical to our performance that we have PlayFabSysHttp and PlayFabWinHttp switched to each use a singleton, static HttpClient.

**Comment by pgilmorepf** [comment] 2017-09-13 18:53
Thanks for reporting this.
The SDK supports more than one API call executing simultaneously, so a single HttpClient isn't sufficient.  

HttpClient is IDisposable, and we're not creating/disposing it properly.
https://github.com/PlayFab/CSharpSDK/blob/master/PlayFabSDK/source/PlayFabHttp/PlayFabSysHttp.cs#L29
The way it's used now, it should be inside of a using(), but it's not.

I could go one of two ways:
I could fix it to dispose the HttpClient properly.
I could probably make a pool of them that get re-used.

For the short term, I'm going to just wrap it in a using() the way it's supposed to be.
I might come back and create a reusable pool of them later.

**Comment by jonbrichoux** [comment] 2017-09-13 19:07
Paul,

Actually please do not wrap the HttpClient in a using. While the fact that it implements IDisposable certainly makes it seems like you should do that, please see many on-line articles on why this is very bad. I can send you a specific reference if you need.

The HttpClient, if used properly, is fully thread-safe and appropriate for multiple simultaneous API calls, and should never be disposed. By “used properly” I mean don’t call any of the methods / properties that set state into it. Use it fully stateless. Also be sure not to pass it to anything (like a DI container) which might dispose it without asking you.

Again, if you read up on the subject you will see that HttpClient’s interface, including the fact that it inherits IDisposable, is very unfortunate in that it suggests usage patterns which are absolutely bad. It should be fully singleton and never disposed.

From the fact that this bug wasn’t logged before, I assume your other customers aren’t writing a lot of high-performance services in .NET. This is a fairly well-known flaw in .NET.


Thanks,

- Jon

**Comment by pgilmorepf** [comment] 2017-09-13 19:28
Alright.  I will carve out some time to confirm your research, and then test it out using a singleton.

I can't give an accurate ETA, since you say the apparent simple fix isn't the right one, and this is unplanned work.

I know that many of the current CSharpSdk users typically use it for admin console tools, where the program starts, executes one or many API calls, and then exits. I don't know of anybody using it for a long-running server process, which is why this issue may not have been caught yet.

I certainly agree that the issue is high priority and should be fixed as soon as possible, but I have to replicate the test conditions and verify that the fix was successful.

Thanks again, and I'll keep you updated here.

**Comment by pgilmorepf** [comment] 2018-01-09 23:57
Hello!
Your suggestions have been committed to our code generator, and they will be part of the next CSharp release:
https://github.com/PlayFab/SDKGenerator/commit/84eb32d8c5b994160e46c652bf5303b52f591d66

I'm going to close this bug, but it won't actually be resolved until the next build (1.23)

**Closed by pgilmorepf** 2018-01-09 23:57 UTC
