### ISSUE TITLE
Deadlock With Synchronization Context

### ISSUE THREAD

**Issue by giawa** [PlayFab/CSharpSDK#94] opened 2017-07-07 14:40 UTC
The PlayFab SDK works well with no context (such as a Console application), but will break if you try to wait for the async methods from a UI thread, or from ASP.NET (which both contain synchronization contexts).  I don't know if this is just a style issue on my end, but to get it to work I had to add ConfigureAwait(false) to each of the async calls.

For example, from PlayFabSysHttp.cs

`httpResponse = await client.PostAsync(fullUrl, postBody).ConfigureAwait(false);`
`httpResponseString = await httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);`

I think this stems from the PlayFab SDK being all async calls, but me wanting to block on some of those calls in the UI code.  I guess the idea with async is that you should be all async or all synchronous, but the PlayFab SDK doesn't provide synchronous methods from what I can see.

What's the suggested work around for this?  Is there a way to simply configure all async calls to have ConfigureAwait(false)?

**Comment by giawa** [comment] 2017-07-07 14:55
Here are examples of similar issues: https://stackoverflow.com/questions/27825467/deadlock-while-blocking-async-httpclient-call-within-a-task-continuation
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

There are two suggested best practices from the blog post above:
 * In your “library” async methods, use ConfigureAwait(false) wherever possible.
 * Don’t block on Tasks; use async all the way down.

I can fix the issue by not blocking, but I actually did want to block in this case...

**Comment by pgilmorepf** [comment] 2017-07-07 17:34
I will accept that there's probably improvements we can make to avoid deadlocking.

However, you should never block your main thread, especially on remote API calls.  Under ideal conditions, those API calls block for 100-300 ms.  Login calls block for almost a full second, and if there's any interruption in your wireless connection (such as with a cellphone in a deadzone) your game will lock up until the API call times out - upto 30 seconds.

ALL of these are noticeable to the user if the UI locks up while waiting.

You should always use .ContinueWith(func) to capture an API result, and your UI should have at minimum an active spinner or other indication that your App is still running.  Even if this is an internal utility program, locking up your whole app is never a good idea.

I'm going to close this, as the "correct" usage is to use .ContinueWith() on all API call tasks.  We always use await for all internal calls.  I'll create a task to check out ConfigureAwait(), but I don't consider that a bug, but rather a feature request, because BY DESIGN, you should not be blocking on our calls.

**Closed by pgilmorepf** 2017-07-07 17:34 UTC

**Comment by giawa** [comment] 2017-07-07 17:59
As an aside, this isn't actually in-game.  These are customer support tools in Windows Forms.  I'm using the Server API for the most part.

**Comment by pgilmorepf** [comment] 2017-07-07 18:17
I get that.  But knowing the difference between "I'm waiting for an API call" and "My program has crashed" is ALWAYS useful.
